### PR TITLE
Use maven_3_latest for 3.8.x, 3.x.x and as default on linux and windows

### PR DESCRIPTION
**Pull request by slawekjaranowski**

### CODE REVIEW

**Review by michael-o — COMMENTED** [review]
Maybe we need `maven3_latest`?

**Review by slachiewicz — APPROVED** [review]

**Comment by slachiewicz** [comment]
If this label exists. Some time ago I left this due to difference on labels for windows/linux

**Comment by slawekjaranowski** [comment]
> Maybe we need `maven3_latest`?

should be present `maven_3_latest`
https://cwiki.apache.org/confluence/display/INFRA/Maven+Installation+Matrix

**Comment by michael-o** [comment]
> > Maybe we need `maven3_latest`?
> 
> should be present `maven_3_latest` https://cwiki.apache.org/confluence/display/INFRA/Maven+Installation+Matrix

This I would use then.

**Comment by slawekjaranowski** [comment]
done with maven_3_latest

**Review by slachiewicz — APPROVED** [review]

**Review by michael-o — APPROVED** [review]

**Pull request merged**
